### ISSUE TITLE
0.2.0_rc2 - message logging file location

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#121]
Edit options of existing configuration and specify log file, on reload this error occurs

2021-12-25 12:45:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry pete.s_ge@ic_ou_.c_m for lennoxs30
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/lennoxs30/__init__.py", line 260, in async_setup_entry
    manager = Manager(
  File "/config/custom_components/lennoxs30/__init__.py", line 361, in __init__
    self._api: s30api_async = s30api_async(
  File "/usr/local/lib/python3.8/site-packages/lennoxs30api/s30api_async.py", line 157, in __init__
    self.message_log = MessageLogger(
  File "/usr/local/lib/python3.8/site-packages/lennoxs30api/message_logger.py", line 19, in __init__
    fileHandler = logging.FileHandler(message_logging_file)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/config/config/s30_messages.log'

**Comment by PeteRager** [comment]
Fix in 0.2.0rc3
