### ISSUE TITLE
0.2.0_rc2 - exception on docker shutdown

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#122]
Cloud Connection
Shutdown docker container

2021-12-25 12:58:29 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/lennoxs30/__init__.py", line 396, in async_shutdown
    await self._api.shutdown()
  File "/usr/local/lib/python3.8/site-packages/lennoxs30api/s30api_async.py", line 240, in shutdown
    await self.logout()
  File "/usr/local/lib/python3.8/site-packages/lennoxs30api/s30api_async.py", line 254, in logout
    resp = await self.post(url, headers=headers, data=None)
  File "/usr/local/lib/python3.8/site-packages/lennoxs30api/s30api_async.py", line 344, in post
    resp = await self._session.post(url, headers=headers, data=data, ssl=self.ssl)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 381, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

**Comment by PeteRager** [comment]
Fixed with changes in API
