### ISSUE TITLE
Temperature Set Error

### ISSUE THREAD

**Issue by garyak** [PeteRager/lennoxs30#13]
Moving set point causes the following error:

```
2021-06-07 17:04:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140289994317200] setCoolSPF() missing 2 required positional arguments: 'scheduleId' and 'tempF'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 548, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/lennoxs30/climate.py", line 289, in async_set_temperature
    await self._system.setCoolSPF(sp)
TypeError: setCoolSPF() missing 2 required positional arguments: 'scheduleId' and 'tempF'
```

This is repeatable by moving temp set point up or down several degrees.

**Comment by PeteRager** [comment]
Looks like I have the wrong version of climate.py in GitHub.  My bad, I should have caught that.  I’ll let you know when  get it sorted out.

**Comment by garyak** [comment]
If it matters, I’m using the custom simple thermostat card instead of the standard version.

**Comment by PeteRager** [comment]
Thanks, that helps.  I looked at it closer, not a version issue.  I missed a branch in the code..  The regular climate card always sends both the high and low set points together.   The simple sends only one.  Looks like a simple change will get to it tomorrow.

**Comment by PeteRager** [comment]
This should be fixed.  Please re-grab this branch and let me know how it works.

https://github.com/PeteRager/lennoxs30/tree/2021.06.11

**Comment by garyak** [comment]
Following two core restarts to get all zones reporting, moving the set point several degrees no longer generates an error in the HA log. I tested on both thermostat cards.

**Comment by garyak** [comment]
Having intermittent issues with reporting still. Can require several core restarts to have both the single zone and multi-zone data displayed.

**Comment by PeteRager** [comment]
I think that 2 restarts issue is a manifestation of not having the "South" S30 show up sometimes.  It's  a race condition on when the messages arrive vs creation of the climate entities.  So you could get just North, just South or both (rarely)

This should no longer happen with the new update for Issue #10

**Comment by PeteRager** [comment]
Do you think this item is now closed?

**Comment by garyak** [comment]
Yes.
