### ISSUE TITLE
Home Assistant 2021.12.7 error

### ISSUE THREAD

**Issue by tteck** [PeteRager/lennoxs30#130]
Logger: homeassistant.util.package
Source: util/package.py:100
First occurred: 2:04:25 PM (3 occurrences)
Last logged: 2:04:50 PM

Unable to install package lennoxs30api==0.1.4: ERROR: Could not find a version that satisfies the requirement lennoxs30api==0.1.4 (from versions: 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0, 0.1.1, 0.1.2) ERROR: No matching distribution found for lennoxs30api==0.1.4 WARNING: You are using pip version 20.2.4; however, version 21.3.1 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

**Comment by tteck** [comment]
Installed v0.2.0 yesterday. First time install. Worked great! Updated to 2021.12.7 and get above error
Can not delete integration in 2021.12.7 restored to 2021.12.6 deleted integration, updated back to 2021.12.7
and can't install integration

**Comment by tteck** [comment]
I changed `  "requirements": ["lennoxs30api==0.1.4"]` to `  "requirements": ["lennoxs30api==0.1.2"]` in the `manifest.json` and get the below error after trying (failing) to add integration

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/lennoxs30/__init__.py:359
Integration: Lennox S30/E30 (documentation)
First occurred: 2:45:38 PM (2 occurrences)
Last logged: 2:45:56 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/lennoxs30/config_flow.py", line 189, in async_step_local
    await self.try_to_connect(user_input)
  File "/config/custom_components/lennoxs30/config_flow.py", line 242, in try_to_connect
    manager = Manager(
  File "/config/custom_components/lennoxs30/__init__.py", line 359, in __init__
    self._api: s30api_async = s30api_async(
TypeError: __init__() got an unexpected keyword argument 'pii_message_logs'

**Comment by PeteRager** [comment]
That looks like an interesting issue.  The integration requires the 0.1.4 api.  So trying to use 0.1.2 would be a problem and will result in that error.  My test system was running at 2021.12.5 and that should work.  I will try upgrading it to 2021.12.7 and see if that works for me.  

In pypi, it shows 0.1.4 being available.  https://pypi.org/project/lennoxs30api/#history

It almost seems like it’s using a cached version.

**Comment by PeteRager** [comment]
So the good news or bad news, is that I upgraded to 2021.12.7 and it works fine for me.  I am running in docker, what are you running in?

**Comment by tteck** [comment]
Docker, I just tried installing the integration again and ........... it worked

**Comment by PeteRager** [comment]
That is interesting and good news!
Here is my guess of what happened.  There was likely some outage / failure on the pypi servers (they must have arrays of these things located at different datacenters around the world) - and the one you were being routed to had a list prior to 2021-12-24 - perhaps as they were trying to recover it.

Indeed they were having a problem:

https://status.python.org/incidents/mhhkwhbc35l7?u=k3txxbbl651p

Thanks for reporting the issue.  Always good to know when something is not working for both me and broader community.
