### ISSUE TITLE
Error after upgrade to v0.2.7 - fast_scan_count not defined in Config

### ISSUE THREAD

**Issue by aaronwatson** [PeteRager/lennoxs30#165]
I have upgraded to v0.2.7 and after reboot I see the following errors:

2022-06-08 18:00:59 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.30.120 for lennoxs30
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/lennoxs30/__init__.py", line 252, in async_setup_entry
fast_poll_count = entry.data[CONF_FAST_POLL_COUNT]
KeyError: 'fast_scan_count'
2022-06-08 18:00:59 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.30.122 for lennoxs30
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/lennoxs30/__init__.py", line 252, in async_setup_entry
fast_poll_count = entry.data[CONF_FAST_POLL_COUNT]
KeyError: 'fast_scan_count'

**Comment by aaronwatson** [comment]
I was able to fix this issue by following the info found here:

https://github.com/PeteRager/lennoxs30/issues/147#issuecomment-1100948023

The "fast_scan_count" and "timeout" entries were missing.

**Comment by PeteRager** [comment]
Interesting, I had thought I had that one fixed :-(.

What version did you upgrade from?

**Comment by aaronwatson** [comment]
I'm not sure which version it was, sorry. Any way to tell from the logs? I know it was earlier than 0.2.0.

**Comment by PeteRager** [comment]
That’s helpful.  Prior to 0.2.0 the configuration was in YAML.  It looks like the migration script would not add these new parameters in that were introduced in 0.2.3 and hence the code would encounter the error you saw.

Does that fit your scenario?

**Comment by aaronwatson** [comment]
Yes, that sounds like the exact issue I encountered. Thanks for your work on this project. It is extremely useful.

**Comment by PeteRager** [comment]
Changes have been merged and release will go out tomorrow.  You do not need to upgrade unless you want.

https://github.com/PeteRager/lennoxs30/releases/tag/v0.2.8
