### ISSUE TITLE
Unable to control the lennox s30 device

### ISSUE THREAD

**Issue by Shameer-Dev21** [PeteRager/lennoxs30#227]
**Describe the bug**
Unable to find a UI component for controlling this device. But the Lennox s30 device is connected. 

Cloud or Local Connection: **Cloud**
State: **connected.**
Version: **2023.1.0 latest**

**Screenshots**
<img width="1680" alt="Screenshot 2023-03-28 at 11 12 38 PM" src="https://user-images.githubusercontent.com/113636182/228489666-a3d0ba0c-8e88-4209-a349-a55f775fa359.png">

**This's issue?**
<img width="1309" alt="Screenshot 2023-03-29 at 4 35 12 PM" src="https://user-images.githubusercontent.com/113636182/228514738-98268966-a148-4091-a9b6-a1db33c5a9a6.png">

**Comment by PeteRager** [comment]
If you go into settings / integrations do you see any devices or entities for the integration?  If so, you can click on the device list and entity list to see them.  For example this is what I see:

![33F89C2F-026F-4A84-9FDE-BC351F5B5701](https://user-images.githubusercontent.com/76050312/228517141-82e77d54-a89d-42ea-bdfa-b6bc4a33403b.jpeg)

**Comment by Shameer-Dev21** [comment]
**Integrations**
<img width="1680" alt="Screenshot 2023-03-29 at 4 53 08 PM" src="https://user-images.githubusercontent.com/113636182/228522027-8c4c875f-203e-4890-a18e-c73390f4f92c.png">

**entities**
<img width="1680" alt="Screenshot 2023-03-29 at 4 56 43 PM" src="https://user-images.githubusercontent.com/113636182/228522036-855ab1d9-1cf9-4016-848b-2f4c53df1aed.png">

**devices**
<img width="1680" alt="Screenshot 2023-03-29 at 4 59 25 PM" src="https://user-images.githubusercontent.com/113636182/228522136-71ca205f-8f02-419c-8bf2-462250a180f9.png">

**Comment by PeteRager** [comment]
Are there any errors or warnings in the log?

Are you using a local connection via IP address or a cloud connection?

**Comment by Shameer-Dev21** [comment]
Via cloud connection. And I got some warnings.

** Warnings in the log**
2023-03-29 16:41:58.173 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-29 16:41:58.179 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration lennoxs30 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-29 16:43:04.731 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lennoxs30
2023-03-29 16:43:41.374 WARNING (MainThread) [custom_components.lennoxs30] async_setup: Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details
2023-03-29 16:46:05.387 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details]
2023-03-29 16:48:28.821 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details]
2023-03-29 16:51:09.760 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details]
2023-03-29 16:53:32.655 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details]
2023-03-29 16:55:59.662 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details]
2023-03-29 16:58:26.018 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details]
2023-03-29 17:00:53.418 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details]
2023-03-29 17:03:19.839 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details]
2023-03-29 17:05:45.685 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details]
2023-03-29 17:08:18.205 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details]
2023-03-29 17:10:41.595 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details]
2023-03-29 17:13:05.275 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried.  Consult the readme for more details]

**Comment by PeteRager** [comment]
Also, in your cloud connection information did you change the default APP ID?

**Comment by Shameer-Dev21** [comment]
> Also, in your cloud connection information did you change the default APP ID?

Yes, I changed last two digits. Ex: mapp0793723676444670468270xx

default: mapp079372367644467046827001

**Comment by PeteRager** [comment]
Should be ok.

**Comment by Shameer-Dev21** [comment]
> Note: I Need the cloud connection to work.

** logs**

**Comment by Shameer-Dev21** [comment]
> That usually doesn't happen. 😀
> 
> We have two choices.
> 
> The first is to reconfigure the integration to use a local connection via IP address to the S30. This assumes it is attached to your local WIFI. You'll need to know it's IP address and make it static in your router. If this is OK, it'll give you a faster more reliable connection.
> 
> If you need the cloud connection to work, the next step will be to enable message logging for the integration and post the log. Instructions are here:
> 
> https://github.com/PeteRager/lennoxs30#reporting-bugs

**Yes, In my end Cloud connection needs to work.**

** logs**
2023-03-29 21:39:36.908 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-29 21:39:36.925 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration lennoxs30 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-29 21:39:54.761 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2023-03-29 21:39:55.170 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=9 from 2022-07-13 11:35:06.181439)
2023-03-29 21:40:27.426 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2023-03-29 21:41:06.677 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lennoxs30
2023-03-29 21:42:06.825 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lennoxs30
2023-03-29 21:42:15.080 WARNING (MainThread) [custom_components.lennoxs30] async_setup: Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried. Consult the readme for more details
2023-03-29 21:42:26.062 ERROR (MainThread) [homeassistant.components.homeassistant_alerts] Timeout fetching homeassistant_alerts data
2023-03-29 21:44:40.714 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried. Consult the readme for more details]
2023-03-29 21:45:38.601 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=34 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=34, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 44463)>
2023-03-29 21:45:38.630 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 99] Address not available, transport: <_SelectorDatagramTransport fd=38 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=38, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::', 60037, 0, 0)>
2023-03-29 21:45:45.757 ERROR (MainThread) [custom_components.lennoxs30] async_setup host [None] unexpected error Code [11] Reference [400] [authenticate Client Connector Error - failed due host not reachable url [https://ic3messaging.myicomfort.com/v1/mobile/authenticate]Message ConnectionKey(host='ic3messaging.myicomfort.com', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None)Message [Errno -3] Try again]
2023-03-29 21:46:03.392 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=21 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=21, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 58264)>
2023-03-29 21:46:03.416 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 99] Address not available, transport: <_SelectorDatagramTransport fd=22 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=22, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::', 43199, 0, 0)>
2023-03-29 21:46:03.424 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=21 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=21, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 58264)>
2023-03-29 21:46:08.631 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=34 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=34, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 44463)>
2023-03-29 21:46:08.640 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 99] Address not available, transport: <_SelectorDatagramTransport fd=38 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=38, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::', 60037, 0, 0)>
2023-03-29 21:46:38.640 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=34 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=34, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 44463)>
2023-03-29 21:46:38.649 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 99] Address not available, transport: <_SelectorDatagramTransport fd=38 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=38, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::', 60037, 0, 0)>
2023-03-29 21:46:50.789 ERROR (MainThread) [custom_components.lennoxs30] async_setup host [None] unexpected error Code [11] Reference [400] [authenticate Client Connector Error - failed due host not reachable url [https://ic3messaging.myicomfort.com/v1/mobile/authenticate]Message ConnectionKey(host='ic3messaging.myicomfort.com', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None)Message [Errno -3] Try again]
2023-03-29 21:47:08.650 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=34 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=34, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 44463)>
2023-03-29 21:47:08.659 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 99] Address not available, transport: <_SelectorDatagramTransport fd=38 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=38, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::', 60037, 0, 0)>
2023-03-29 21:47:39.829 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 551, in aiohttp.http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2023-03-29 21:47:39.858 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
messages, upgraded, tail = self.request_parser.feed_data(data)
File "aiohttp/http_parser.pyx", line 551, in aiohttp.http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2023-03-29 21:49:18.235 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried. Consult the readme for more details]
2023-03-29 21:50:35.256 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry [sh_m_e_d_v@re_er_yt_ch.co](mailto:sh_m_e_d_v@re_er_yt_ch.co) for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
result = await component.async_unload_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/sensor/init.py", line 137, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-03-29 21:50:35.277 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry [sh_m_e_d_v@re_er_yt_ch.co](mailto:sh_m_e_d_v@re_er_yt_ch.co) for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
result = await component.async_unload_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/binary_sensor/init.py", line 175, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-03-29 21:50:35.302 ERROR (MainThread) [custom_components.lennoxs30] async_unload_entry call to hass.config_entries.async_unload_platforms returned False
2023-03-29 21:51:49.713 WARNING (MainThread) [custom_components.lennoxs30] async_setup: host [None] Code [15] Reference [1] [Timeout waiting for configuration data from Lennox - this sometimes happens, the connection will be automatically retried. Consult the readme for more details]
2023-03-29 21:52:51.294 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry [sh_m_e_d_v@re_er_yt_ch.co](mailto:sh_m_e_d_v@re_er_yt_ch.co) for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
result = await component.async_unload_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/sensor/init.py", line 137, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-03-29 21:52:51.303 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry [sh_m_e_d_v@re_er_yt_ch.co](mailto:sh_m_e_d_v@re_er_yt_ch.co) for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
result = await component.async_unload_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/binary_sensor/init.py", line 175, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-03-29 21:52:51.320 ERROR (MainThread) [custom_components.lennoxs30] async_unload_entry call to hass.config_entries.async_unload_platforms returned False

**Comment by PeteRager** [comment]
That log shows network errors.  Both from the Lennox Integration as well as the Home Assistant discovery.  I just tested going to https://ic3messaging.myicomfort.com/v1/mobile/authenticate in my browser and it is able to connect.   

```
2023-03-29 21:46:50.789 ERROR (MainThread) [custom_components.lennoxs30] async_setup host [None] unexpected error Code [11] Reference [400] [authenticate Client Connector Error - failed due host not reachable url [https://ic3messaging.myicomfort.com/v1/mobile/authenticate]Message ConnectionKey(host='ic3messaging.myicomfort.com', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None)Message [Errno -3] Try again]
2023-03-29 21:47:08.650 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=34 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=34, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 44463)>
```

There is also a message about the RPI having low voltage, which could be related.

**Comment by Shameer-Dev21** [comment]
Note: In this place there is only a Lennox thermostat. There are no additional sensors there.

**s30_lennox.log file**
[s30_lennox.log](https://github.com/PeteRager/lennoxs30/files/11103757/s30_lennox.log)

**Comment by PeteRager** [comment]
Thanks for sending the message log file,   

The data in there shows that the thermostat is online


```
    "myPresence": {
        "db8af39c-5e15-4595-8c48-1cab015df46a": "online"
    }
```

The integration then establishes subscriptions to the topics and Lennox returns OK.

```
2023-03-29 18:29:59,718 [MainThread  ] [DEBUG]  {
    "MessageType": "RequestData",
    "SenderID": "**redacted**",
    "MessageID": "b030e370-4502-40fd-a0b0-7d05de75b2ea",
    "TargetID": "db8af39c-5e15-4595-8c48-1cab015df46a",
    "AdditionalParameters": {
        "JSONPath": "1;/system;/zones;/occupancy;/schedules;"
    }
}
2023-03-29 18:30:00,257 [MainThread  ] [DEBUG]  {
    "code": 1,
    "message": "Ok",
    "retry_after": 0
}
2023-03-29 18:30:00,259 [MainThread  ] [DEBUG]  {
    "MessageType": "RequestData",
    "SenderID": "**redacted**",
    "MessageID": "8b453cca-3043-4f1b-96d4-546744b49b5d",
    "TargetID": "db8af39c-5e15-4595-8c48-1cab015df46a",
    "AdditionalParameters": {
        "JSONPath": "1;/reminderSensors;/reminders;/alerts/active;/alerts/meta;/dealers;/devices;/equipments;/fwm;/ocst;"
    }
}
2023-03-29 18:30:00,876 [MainThread  ] [DEBUG]  {
    "code": 1,
    "message": "Ok",
    "retry_after": 0
}
```

But then no messages are received within the timeout and then it retries and the whole sequence starts again.

It may be that we are not waiting long enough for the configuration to come in.  The parameter defaults to 30 seconds.  Let's set it to 120 seconds.  Go to settings/integrations, press configure and enter 120 into the field called "Configuration Wait Time in Seconds".  Reload the integration or restart HASS.  See if it works, if not change the App ID and restart again.  

https://github.com/PeteRager/lennoxs30#advanced-configuration

**Comment by PeteRager** [comment]
> Also I have one more doubt. how to refresh token works here?
> 
> https://ic3messaging.myicomfort.com/v1/mobile/authenticate
> 
> Here we get auth_token and refresh_token right?
> 
> After this how to handle the refresh token flow?

The Lennox app doesn't use standard oauth flow, the refresh token while recorded is not used (as i was unable to find an example of how to use it), if the token expires, the integration gets an error and then reestablishes the flow.   The code for all of that is off in the lennoxs30api GitHub repo.

**Comment by PeteRager** [comment]
I'm going to run some tests tonite on the cloud connection, to verify it still works for me.

**Comment by Shameer-Dev21** [comment]
> Thanks for sending the message log file,
> 
> The data in there shows that the thermostat is online
> 
> ```
>     "myPresence": {
>         "db8af39c-5e15-4595-8c48-1cab015df46a": "online"
>     }
> ```
> 
> The integration then establishes subscriptions to the topics and Lennox returns OK.
> 
> ```
> 2023-03-29 18:29:59,718 [MainThread  ] [DEBUG]  {
>     "MessageType": "RequestData",
>     "SenderID": "**redacted**",
>     "MessageID": "b030e370-4502-40fd-a0b0-7d05de75b2ea",
>     "TargetID": "db8af39c-5e15-4595-8c48-1cab015df46a",
>     "AdditionalParameters": {
>         "JSONPath": "1;/system;/zones;/occupancy;/schedules;"
>     }
> }
> 2023-03-29 18:30:00,257 [MainThread  ] [DEBUG]  {
>     "code": 1,
>     "message": "Ok",
>     "retry_after": 0
> }
> 2023-03-29 18:30:00,259 [MainThread  ] [DEBUG]  {
>     "MessageType": "RequestData",
>     "SenderID": "**redacted**",
>     "MessageID": "8b453cca-3043-4f1b-96d4-546744b49b5d",
>     "TargetID": "db8af39c-5e15-4595-8c48-1cab015df46a",
>     "AdditionalParameters": {
>         "JSONPath": "1;/reminderSensors;/reminders;/alerts/active;/alerts/meta;/dealers;/devices;/equipments;/fwm;/ocst;"
>     }
> }
> 2023-03-29 18:30:00,876 [MainThread  ] [DEBUG]  {
>     "code": 1,
>     "message": "Ok",
>     "retry_after": 0
> }
> ```
> 
> But then no messages are received within the timeout and then it retries and the whole sequence starts again.
> 
> It may be that we are not waiting long enough for the configuration to come in. The parameter defaults to 30 seconds. Let's set it to 120 seconds. Go to settings/integrations, press configure and enter 120 into the field called "Configuration Wait Time in Seconds". Reload the integration or restart HASS. See if it works, if not change the App ID and restart again.
> 
> https://github.com/PeteRager/lennoxs30#advanced-configuration

Still the same issue but device connected. I tried more than 10 times. After changing the values "Configuration Wait Time in Seconds": 60 to 120.

** Screenshots**
<img width="1415" alt="Screenshot 2023-03-30 at 5 25 28 PM" src="https://user-images.githubusercontent.com/113636182/228830667-8fe469ea-0c92-49ca-9910-8659023bcf88.png">

<img width="431" alt="Screenshot 2023-03-30 at 5 26 24 PM" src="https://user-images.githubusercontent.com/113636182/228830696-cff42dcf-ca22-447f-9db8-42aa54acae5b.png">

**Comment by Shameer-Dev21** [comment]
> I verified the integration works with my cloud account. I get the data within 3 seconds of sending the subscription.

That's great. It's showing the device control UI component is visible?

**Comment by Shameer-Dev21** [comment]
> 

Ok Thanks. 

What is your suggestion for a refresh token? Do you have any ideas?

Currently My testing refresh token function logic is, If the token is expired -> login again and i'm getting the latest token for now. I'll follow the same process all the time. Will this take some issue in future?

**Comment by PeteRager** [comment]
Someth8ng is definitely not right

Are there any additional errors / warnings in the home assistant log?

The next steps is to enable debug logging in home assistant for the integration.  Put this is your configuration.yaml, restart HASS, and post the home-assistant.log file.  This will show us the detailed steps the code is taking.

```
logger:
  default: warning
  logs:
    custom_components.lennoxs30: debug
    lennoxs30api: debug
```

It'd also be good to understand the version of software on the S30.  On the thermostat panel, go to general/about and find the thermostat control software revision (mine is 03.81.0213) and the smarthub controller software version (mine is 03.89.0723)

You may also want to power cycle or reboot the S30.  You can also try deleting the integration and reconfiguring it using all the defaults.   

I had one user who saw this issue 18 months ago and changing the app Id fixed it.

**Comment by PeteRager** [comment]
If you are trying to determine the communication flow, the best bet it to look at the code in this repo:

https://github.com/PeteRager/lennoxs30api

If you have an iPhone with the Lennox app on it, you can run it through a proxy like Burp to understand the data flow.  If our current steps don't yield anything that will be the next step.

**Comment by PeteRager** [comment]
Has the issue resolved?

**Comment by Shameer-Dev21** [comment]
> Has the issue resolved?

Still the same issues. Device only connected. And I'm not getting errors / warnings in the home assistant log.

**Comment by PeteRager** [comment]
Sorry to hear that,  I did give you some follow up steps. Let me know if you have questions on those..

**Comment by PeteRager** [comment]
Automatic close due to inactivity
