### ISSUE TITLE
Integration not loading after recent HA and Integration update

### ISSUE THREAD

**Issue by mbirkes** [PeteRager/lennoxs30#319]
**Describe the bug**
Integration no longer loading devices after HA update 2024.3.3

**To Reproduce**
Steps to reproduce the behavior: udated HA 2024.3.3 with Cloud connection to M30 devices

**Expected behavior**
The integration is no longer loading after the recent HA update. I'm not sure if it is the update or something else, but restarts of HA and the integration do not resolve it. 

**Screenshots/Logs**
2 error logs pasted below:

#1
This error originated from a custom integration.

Logger: custom_components.lennoxs30
Source: custom_components/lennoxs30/__init__.py:383
integration: Lennox S30/E30 (documentation, issues)
First occurred: 11:23:26 AM (2 occurrences)
Last logged: 11:29:56 AM

async_unload_entry call to hass.config_entries.async_unload_platforms returned False

----------------------------------------
#1
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/lennoxs30/device.py:281
integration: Lennox S30/E30 (documentation, issues)
First occurred: March 31, 2024 at 2:23:18 PM (1 occurrences)
Last logged: March 31, 2024 at 2:23:18 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/lennoxs30/__init__.py", line 687, in initialize_retry_task
    await self.s30_initialize()
  File "/config/custom_components/lennoxs30/__init__.py", line 548, in s30_initialize
    await self.create_devices()
  File "/config/custom_components/lennoxs30/__init__.py", line 673, in create_devices
    z.register_device()
  File "/config/custom_components/lennoxs30/device.py", line 281, in register_device
    name=self._system.name + "_" + self._zone.name,
         ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

![image](https://github.com/PeteRager/lennoxs30/assets/272836/d42106a3-3a71-40ba-86c8-5100aca729b5)


**Version**
 - Home Assistant: 2024.3.3
 - This Integration: 2024.3.0
 

**Integration Configuration **
- Cloud or Local Connection: Cloud
- Inverter or Sensor Diagnostics Enabled: no

**Additional context**
Add any other context about the problem here.

**Comment by mbirkes** [comment]
I found another log, seems to indicate connection issues:

This error originated from a custom integration.

Logger: custom_components.lennoxs30
Source: custom_components/lennoxs30/__init__.py:953
integration: Lennox S30/E30 (documentation, issues)
First occurred: March 31, 2024 at 11:20:08 PM (4 occurrences)
Last logged: 10:54:06 AM

messagePump communication error host [None] Code [11] Reference [300] [messagePump failed - Communication TimeoutError exceeded configured timeout [https://icretrieveapi.myicomfort.com/v1/messages/retrieve]]
messagePump communication error host [None] Code [11] Reference [400] [messagePump Client Connector Error - failed due host not reachable url [https://icretrieveapi.myicomfort.com/v1/messages/retrieve]Message ConnectionKey(host='icretrieveapi.myicomfort.com', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None)Message SSL handshake is taking longer than 60.0 seconds: aborting the connection]

**Comment by PeteRager** [comment]
I'd like to see the sequence of errors.  Stop home assistant, restart it, wait 5 minutes, grab the home-assistant.log and attach it to this issue.

**Comment by PeteRager** [comment]
I tested the cloud connection to my S30 using ha 2023.3.0 and 2023.3.0 of this integration and it works for me.

we should enable debug logging on your system so we have all the details, info on how to configure is here:

https://github.com/PeteRager/lennoxs30?tab=readme-ov-file#reporting-bugs

Also check the internet connection on the thermostats.  Are you able to connect using their mobile app?

How are you running HA?

**Comment by mbirkes** [comment]
Thanks for confirming. I'll gather some additional information.  I'm running HA x86 on metal. The M30 devices are fine in the native app with cloud connection. My integration stopped working sometime while updating my various HACS components (including this one) and HA upgrade from 2024.3.1. to 3.3.  I'm not sure exactly of the sequencing or when it failed. Nothing else purposely changed other than the system and component updates.

**Comment by mbirkes** [comment]
Well, after several reboots and setting up logging settings, the integration began to work eventually this final time. Apologies for opening the issue, but my prior attempts over the last couple days had failed. I'll include the final log here for your review if you'd like to retro anything. 
[home-assistant.log](https://github.com/PeteRager/lennoxs30/files/14845884/home-assistant.log)
