### ISSUE TITLE
Error while setting up lennoxs30 platform for sensor

### ISSUE THREAD

**Issue by garyak** [PeteRager/lennoxs30#33]
Following update and restart to HA Core 2021.7.3:

```
2021-07-16 06:42:54 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up lennoxs30 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/lennoxs30/sensor.py", line 42, in async_setup_platform
    sensor = S30OutdoorTempSensor(hass, manager, system)
  File "/config/custom_components/lennoxs30/sensor.py", line 65, in __init__
    self._myname = self._system.name + "_outdoor_temperature"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2021-07-16 06:43:25 ERROR (MainThread) [lennoxs30api.s30api_async] executeOnUpdateCallback - failed 'S30OutdoorTempSensor' object has no attribute '_myname'
2021-07-16 06:43:25 ERROR (MainThread) [lennoxs30api.s30api_async] executeOnUpdateCallback - failed 'S30OutdoorTempSensor' object has no attribute '_myname'
2021-07-16 06:43:25 ERROR (MainThread) [lennoxs30api.s30api_async] executeOnUpdateCallback - failed 'S30OutdoorTempSensor' object has no attribute '_myname'
2021-07-16 06:43:25 ERROR (MainThread) [lennoxs30api.s30api_async] executeOnUpdateCallback - failed 'S30OutdoorTempSensor' object has no attribute '_myname'
```
Errors are continuous and varied:

```
2021-07-16 06:47:40 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 395, in async_update_ha_state
    f"No entity id specified for entity {self.name}"
  File "/config/custom_components/lennoxs30/climate.py", line 152, in name
    return self._myname
AttributeError: 'S30Climate' object has no attribute '_myname'
```
Subsequent restart produced no errors. I have to learn to restart several times before reporting errors I guess :-)

**Comment by PeteRager** [comment]
Thanks for writing this up.  It should start fine every time!  If it fails that’s an issue.

The underlying issues is the order in which Lennox sends the information at startup is not always the same.  With the information provided we should be able to fix and make sure it doesn’t happen again.
