### ISSUE TITLE
ERROR messagePump - unexpected exception

### ISSUE THREAD

**Issue by garyak** [PeteRager/lennoxs30#340]
**Describe the bug**
Seen in HA log.  No clear correlation with HVAC activity. 

**Screenshots/Logs**
```
2024-08-29 20:25:57.409 ERROR (MainThread) [lennoxs30api.s30api_async] messagePump - unexpected exception - please raise an issue to track
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/lennoxs30api/s30api_async.py", line 706, in messagePump
    resp_json = json.loads(resp_txt)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 1976 (char 1975)
```
**Version**
 - Home Assistant:
 - Core 2024.8.3
 - Supervisor 2024.08.0
 - Operating System 13.1
 - Frontend 20240809.0
 - This Integration: 2024.8.0
 
**Integration Configuration **
- Cloud or Local Connection: Local
- Inverter or Sensor Diagnostics Enabled: No

**Comment by PeteRager** [comment]
It looks like the message sent from the s30 was unable to be parsed.  Unfortunately, the error handling does not log the message text that failed to parse and we don't have info on the root cause. That need to be enhanced so we can see what is in the message that has improper formatting.

What version firmware is on the S30s. Easiest place to find is on the s30 device for the integration.  

![IMG_3169](https://github.com/user-attachments/assets/8e582d40-a1fc-438e-ae29-0217688656f9)

**Comment by garyak** [comment]
Two s30's 
- 3.81.207 - South
- 3.81.213 - North

**Comment by PeteRager** [comment]
This is a strange error.  Has this been reoccuring?  I'm going to update the API to log the text of the message that fails to decode.

**Comment by garyak** [comment]
This has not been a reoccurring error.
