### ISSUE TITLE
Module lennoxs30api cannot be loaded

### ISSUE THREAD

**Issue by gravufo** [PeteRager/lennoxs30#353]
**Describe the bug**
I'm getting the following error when HA tries to load the integration:
![image](https://github.com/user-attachments/assets/c969b023-4c31-4955-9590-909386558286)

**Version**
 - Home Assistant: `ghcr.io/home-assistant/home-assistant:stable` which is currently `2024.12.5`
 - This Integration: `2024.11.0` installed through HACS

**Integration Configuration**
- Cloud or Local Connection: Cloud (using M30)
- Inverter or Sensor Diagnostics Enabled: No

**Additional context**
Running in Kubernetes (k3s) using a volume mount for persistence. This integration was working fine for multiple years and it just suddenly stopped working.

Any idea what could have caused this? I'm a computer engineer, so I can definitely help troubleshoot. I just wanted to know if there was a known issue or easy known fix before I go further.

**Comment by gravufo** [comment]
Thanks a lot for the quick answer!

Restarting doesn't work, I had tried that multiple times. I even tried "redownload" in HACS.
Here are the full logs on startup:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun home-assistant (no readiness notification)
s6-rc: info: service legacy-services successfully started
2024-12-22 15:41:30.382 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration lennoxs30 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 15:41:30.417 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-22 15:41:44.374 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'lennoxs30': Unable to import component: No module named 'lennoxs30api'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/lennoxs30/__init__.py", line 32, in <module>
    from lennoxs30api.s30exception import EC_COMMS_ERROR, EC_CONFIG_TIMEOUT
ModuleNotFoundError: No module named 'lennoxs30api'
```

I do indeed see the entry in the manifest:
```bash
homeassistant-769cb5c98b-lz2wx:/config# cat custom_components/lennoxs30/manifest.json
{
  "domain": "lennoxs30",
  "name": "Lennox S30/E30",
  "codeowners": ["@PeteRager"],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://github.com/PeteRager/lennoxs30/blob/master/README.MD",
  "iot_class": "local_push",
  "issue_tracker" : "https://github.com/PeteRager/lennoxs30/issues",
  "quality_scale": "platinum",
  "requirements": ["lennoxs30api==0.2.16"],
  "version": "2024.11.0"
}
```

Installing manually works, but is not persistent across restarts:
```bash
homeassistant-769cb5c98b-lz2wx:/config# pip install lennoxs30api==0.2.16
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting lennoxs30api==0.2.16
  Downloading lennoxs30api-0.2.16-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.13/site-packages (from lennoxs30api==0.2.16) (3.11.11)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.13/site-packages (from aiohttp->lennoxs30api==0.2.16) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.13/site-packages (from aiohttp->lennoxs30api==0.2.16) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/site-packages (from aiohttp->lennoxs30api==0.2.16) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/site-packages (from aiohttp->lennoxs30api==0.2.16) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/site-packages (from aiohttp->lennoxs30api==0.2.16) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/site-packages (from aiohttp->lennoxs30api==0.2.16) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/site-packages (from aiohttp->lennoxs30api==0.2.16) (1.18.3)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.13/site-packages (from yarl<2.0,>=1.17.0->aiohttp->lennoxs30api==0.2.16) (3.10)
Downloading lennoxs30api-0.2.16-py3-none-any.whl (46 kB)
Installing collected packages: lennoxs30api
Successfully installed lennoxs30api-0.2.16
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
```

Doing `pip install` installs it in the wrong folder (`/usr/local/lib/python3.13/site-packages` instead of `/config/deps`.

I also just tested reverting to HA 2024.11 and it seems to have fixed the issue, although it now issues an error for another integration. I suspect they broke something in the dependency restore. I will stay on this version for the time being.

Sorry for the false alarm!

**Comment by PeteRager** [comment]
I'll give it a try on 2024.12.x

**Comment by PeteRager** [comment]
Looks like there are similar reported issues in Ha Github.  There is this PR that is in progress, is approved and may address the issue.  If I'm reading it right, there's some breakages when running the container not in docker, which sounds like your environment.  

https://github.com/home-assistant/core/pull/132404

**Comment by gravufo** [comment]
Nice find! Indeed, I run in Kubernetes, so any "restart" (except failures on the liveness probe) is a brand new container, hence why changes are not persistent across restarts unless done in volumes.
I'll follow that PR and try updating once it's released!
